FROM java:openjdk-8-jre-alpine

ARG VERSION={{ breakerbox_docker_version }}

LABEL name="breakerbox" version=$VERSION

RUN mkdir /opt \
    && apk update \
    && apk add ca-certificates wget \
    && update-ca-certificates \
    && wget -q -O - https://github.com/yammer/breakerbox/releases/download/breakerbox-parent-$VERSION/breakerbox-$VERSION.tar.gz | tar -xzf - -C /opt

EXPOSE 8080 8081

WORKDIR /opt

VOLUME ["/opt"]

ENTRYPOINT ["java", "-jar", "breakerbox-service-{{ breakerbox_docker_version }}.jar"]
CMD ["server", "breakerbox.yml"]
